FROM openjdk:17-jdk as builder
ARG JAR_FILE=build/libs/*.jar
ADD ${JAR_FILE} app.jar

FROM openjdk:17-jdk-slim
COPY --from=builder /app.jar /app.jar

ENV TZ=Asia/Seoul
ENV ACCESS_EXP=$ACCESS_EXP
ENV API_KEY=$API_KEY
ENV API_SECRET=$API_SECRET
ENV BUCKET=$BUCKET
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_URL=$DB_URL
ENV DB_USER=$DB_USER
ENV DIRECTORY=$DIRECTORY
ENV IAM_ACCESS=$IAM_ACCESS
ENV IAM_SECRET=$IAM_SECRET
ENV JWT_SECRET=$JWT_SECRET
ENV REFRESH_EXP=$REFRESH_EXP
ENV SENDER=$SENDER
ENV REDIS_HOST=$REDIS_HOST

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app.jar"]