spring:

  # format
  jackson:
    property-naming-strategy: SNAKE_CASE

  # jdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: 1

  # jpa
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

# server
server:
  port: ${SERVER_PORT:8080}

# logging
logging:
  level:
    root: info

# SMS
sms:
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}
  sender: ${SENDER}

jwt:
  secret-key: ${JWT_SECRET}
  access-exp: ${ACCESS_EXP}
  refresh-exp: ${REFRESH_EXP}